language: node_js

node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add codecov greenkeeper-lockfile

before_script: greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn test

after_script:
  - codecov
  - greenkeeper-lockfile-upload
